/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Sponsor;
import Model.FundRaising.FundRaising;
import Model.Sponsor.Sponsor;
import Model.UserAccount.UserAccount;
import Model.Ecosystem;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
/**
 *
 * @author varshakuruva
 */
public class SponsorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    JPanel ipcUserProcessContainer;
    Ecosystem ipcSystem;
    private UserAccount ipcAccount;
    public SponsorWorkArea(JPanel ipcUserProcessContainer, UserAccount ipcAccount, Ecosystem ipcSystem) {
        initComponents();
        this.ipcUserProcessContainer = ipcUserProcessContainer;
        this.ipcSystem = ipcSystem;
        this.ipcAccount = ipcAccount;
        ipcPopulateTable();
    }

    
    public void ipcPopulateTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tbSponsorPetOwnerInfo.getModel();

        tablemodel.setRowCount(0);
        for(Sponsor sponsor : ipcSystem.getSponsorDirectory().getSponsorDirectory()) {
            Object[] row= new Object[4];
            row[0] = sponsor;
            row[1] = sponsor.getIpcpetOwner();
            row[2] = sponsor.getIpcpetType();
            row[3] = sponsor.getIpchospitalName();
            tablemodel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbSponsorPetOwnerInfo = new javax.swing.JTable();
        btnApprove1 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        jPanelSponsor = new javax.swing.JPanel();
        lbManageInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSponsorPetOwnerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sponsor", "Pet owner", "Pet type", "Hospital name"
            }
        ));
        jScrollPane1.setViewportView(tbSponsorPetOwnerInfo);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 650, 300));

        btnApprove1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnApprove1.setForeground(new java.awt.Color(102, 0, 0));
        btnApprove1.setText("APPROVE SPONSOR");
        btnApprove1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApprove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprove1ActionPerformed(evt);
            }
        });
        add(btnApprove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 169, 34));

        lbl1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(102, 0, 0));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("SPONSOR APPROVAL");
        add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 150, 399, 42));

        jPanelSponsor.setBackground(new java.awt.Color(102, 0, 0));

        lbManageInfo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbManageInfo.setForeground(new java.awt.Color(255, 255, 255));
        lbManageInfo.setText("SPONSOR WORK AREA");

        javax.swing.GroupLayout jPanelSponsorLayout = new javax.swing.GroupLayout(jPanelSponsor);
        jPanelSponsor.setLayout(jPanelSponsorLayout);
        jPanelSponsorLayout.setHorizontalGroup(
            jPanelSponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSponsorLayout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addComponent(lbManageInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        jPanelSponsorLayout.setVerticalGroup(
            jPanelSponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSponsorLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lbManageInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelSponsor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApprove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprove1ActionPerformed
        // TODO add your handling code here:

        int selectedRow = tbSponsorPetOwnerInfo.getSelectedRow();
        Sponsor sponsorRowSelected = (Sponsor) tbSponsorPetOwnerInfo.getValueAt(selectedRow, 0);
        for(FundRaising fundRaising: ipcSystem.getFundRaisingDirectory().getFundRaisingDirectory()) {
            if(sponsorRowSelected.getIpcpetOwner().equals(fundRaising.getIpcpetOwner())) {
                ipcSystem.getFundRaisingDirectory().updateFundRaisingSponsorStatus(fundRaising, "Approved");
            }
        }

        JOptionPane.showMessageDialog(this,"Successful Approval of Funds!");
    }//GEN-LAST:event_btnApprove1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove1;
    private javax.swing.JPanel jPanelSponsor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbManageInfo;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTable tbSponsorPetOwnerInfo;
    // End of variables declaration//GEN-END:variables
}
