/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalAdmin;

import Model.Ecosystem;
import java.awt.CardLayout;
import Model.UserAccount.UserAccount;
import UserInterface.SystemAdminWorkArea.ManagePetVolunteer;
import javax.swing.JPanel;
import UserInterface.HospitalAdmin.ManageLabAssistant;


/**
 *
 * @author saran
 */
public class HospitalAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkArea
     */
    JPanel ipcUserProcessContainer;
    Ecosystem ipcSystem;
    private UserAccount ipcAccount;
    public HospitalAdminWorkArea(JPanel ipcUserProcessContainer,UserAccount ipcAccount, Ecosystem ipcSystem) {
        initComponents();
        this.ipcUserProcessContainer = ipcUserProcessContainer;
        this.ipcSystem = ipcSystem;
        this.ipcAccount = ipcAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        ManageLabAssitant = new javax.swing.JPanel();
        lb3 = new javax.swing.JLabel();
        ManageHospitalInfo = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        ManagePet = new javax.swing.JPanel();
        lb4 = new javax.swing.JLabel();
        ManageVet = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        ManageSponsor = new javax.swing.JPanel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        backgroundPanel.setBackground(new java.awt.Color(204, 204, 204));

        sidepane.setBackground(new java.awt.Color(102, 0, 51));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageLabAssitant.setBackground(new java.awt.Color(255, 204, 204));

        lb3.setBackground(new java.awt.Color(255, 204, 204));
        lb3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lb3.setForeground(new java.awt.Color(153, 0, 51));
        lb3.setText("Manage LabAssistant");
        lb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageLabAssitantLayout = new javax.swing.GroupLayout(ManageLabAssitant);
        ManageLabAssitant.setLayout(ManageLabAssitantLayout);
        ManageLabAssitantLayout.setHorizontalGroup(
            ManageLabAssitantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageLabAssitantLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        ManageLabAssitantLayout.setVerticalGroup(
            ManageLabAssitantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLabAssitantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(ManageLabAssitant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, 50));

        ManageHospitalInfo.setBackground(new java.awt.Color(255, 204, 204));

        lb1.setBackground(new java.awt.Color(187, 177, 205));
        lb1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lb1.setForeground(new java.awt.Color(153, 0, 51));
        lb1.setText("Manage Hospital Info");
        lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageHospitalInfoLayout = new javax.swing.GroupLayout(ManageHospitalInfo);
        ManageHospitalInfo.setLayout(ManageHospitalInfoLayout);
        ManageHospitalInfoLayout.setHorizontalGroup(
            ManageHospitalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageHospitalInfoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        ManageHospitalInfoLayout.setVerticalGroup(
            ManageHospitalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageHospitalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(ManageHospitalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 50));

        ManagePet.setBackground(new java.awt.Color(255, 204, 204));

        lb4.setBackground(new java.awt.Color(187, 177, 205));
        lb4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lb4.setForeground(new java.awt.Color(153, 0, 0));
        lb4.setText("Manage Pet Info");
        lb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManagePetLayout = new javax.swing.GroupLayout(ManagePet);
        ManagePet.setLayout(ManagePetLayout);
        ManagePetLayout.setHorizontalGroup(
            ManagePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagePetLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        ManagePetLayout.setVerticalGroup(
            ManagePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagePetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(ManagePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 50));

        ManageVet.setBackground(new java.awt.Color(255, 204, 204));
        ManageVet.setForeground(new java.awt.Color(0, 153, 153));

        lb2.setBackground(new java.awt.Color(255, 204, 204));
        lb2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lb2.setForeground(new java.awt.Color(153, 0, 51));
        lb2.setText("Manage Vet");
        lb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageVetLayout = new javax.swing.GroupLayout(ManageVet);
        ManageVet.setLayout(ManageVetLayout);
        ManageVetLayout.setHorizontalGroup(
            ManageVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageVetLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        ManageVetLayout.setVerticalGroup(
            ManageVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageVetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        sidepane.add(ManageVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 260, 50));

        ManageSponsor.setBackground(new java.awt.Color(255, 204, 204));

        lb5.setBackground(new java.awt.Color(153, 0, 51));
        lb5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lb5.setForeground(new java.awt.Color(153, 0, 51));
        lb5.setText("Manage Sponsor");
        lb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout ManageSponsorLayout = new javax.swing.GroupLayout(ManageSponsor);
        ManageSponsor.setLayout(ManageSponsorLayout);
        ManageSponsorLayout.setHorizontalGroup(
            ManageSponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageSponsorLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        ManageSponsorLayout.setVerticalGroup(
            ManageSponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageSponsorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        sidepane.add(ManageSponsor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        lb6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lb6.setForeground(new java.awt.Color(255, 255, 255));
        lb6.setText("Logged as a hospital..");
        sidepane.add(lb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 250, -1));

        jLabel1.setBackground(new java.awt.Color(207, 207, 207));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/m1.gif"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lb3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3MousePressed
        // TODO add your handling code here:
        ManageLabAssistant manageLabAssistantJPanel = new ManageLabAssistant(ipcUserProcessContainer,ipcAccount, ipcSystem);
        ipcUserProcessContainer.add("ManageLabAssistant", manageLabAssistantJPanel);
        CardLayout layout = (CardLayout) ipcUserProcessContainer.getLayout();
        layout.next(ipcUserProcessContainer);
    }//GEN-LAST:event_lb3MousePressed

    private void lb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MousePressed
        // TODO add your handling code here:
        ManageHospitalInfo manageHospitalInfoJPanel = new ManageHospitalInfo(ipcUserProcessContainer,ipcAccount, ipcSystem);
        ipcUserProcessContainer.add("ManageHospitalInfo", manageHospitalInfoJPanel);
        CardLayout layout = (CardLayout) ipcUserProcessContainer.getLayout();
        layout.next(ipcUserProcessContainer);
    }//GEN-LAST:event_lb1MousePressed

    private void lb4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb4MousePressed
        // TODO add your handling code here:

        ManagePetInfo managePetInfoJPanel = new ManagePetInfo(ipcUserProcessContainer,ipcAccount, ipcSystem);
        ipcUserProcessContainer.add("ManagePetInfo", managePetInfoJPanel);
        CardLayout layout = (CardLayout) ipcUserProcessContainer.getLayout();
        layout.next(ipcUserProcessContainer);
    }//GEN-LAST:event_lb4MousePressed

    private void lb2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MousePressed
        // TODO add your handling code here:
        ManageVet manageVetJPanel = new ManageVet(ipcUserProcessContainer, ipcAccount, ipcSystem);
        ipcUserProcessContainer.add("ManageVet", manageVetJPanel);
        CardLayout layout = (CardLayout) ipcUserProcessContainer.getLayout();
        layout.next(ipcUserProcessContainer);
    }//GEN-LAST:event_lb2MousePressed

    private void lb5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb5MousePressed
        // TODO add your handling code here:
        ManageSponsor manageSponsorJPanel = new ManageSponsor(ipcUserProcessContainer,ipcAccount, ipcSystem);
        ipcUserProcessContainer.add("ManageSponsorInfo", manageSponsorJPanel);
        CardLayout layout = (CardLayout) ipcUserProcessContainer.getLayout();

        layout.next(ipcUserProcessContainer);

    }//GEN-LAST:event_lb5MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ManageHospitalInfo;
    private javax.swing.JPanel ManageLabAssitant;
    private javax.swing.JPanel ManagePet;
    private javax.swing.JPanel ManageSponsor;
    private javax.swing.JPanel ManageVet;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
