/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.HospitalAdmin;

/**
 *
 * @author saran
 */

import IntensivePetCare.Ecosystem;
import IntensivePetCare.Hospital.Hospital;
import IntensivePetCare.LabAssistant.LabAssistant;
import IntensivePetCare.Role.LabAssistantRole;
import IntensivePetCare.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageLabAssistant extends javax.swing.JPanel {

    /**
     * Creates new form ManageLabAssistant
     */
    JPanel ipcuserProcessContainer;
    Ecosystem ipcsystem;
    private UserAccount ipcaccount;

    public ManageLabAssistant(JPanel ipcuserProcessContainer, UserAccount ipcaccount, Ecosystem ipcsystem) {
        initComponents();
        this.ipcuserProcessContainer = ipcuserProcessContainer;
        this.ipcsystem = ipcsystem;
        this.ipcaccount = ipcaccount;
        ipcpopulateLabAssistantTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLabAssistant = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblManageInfo1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 40));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE LAB ASSITANT ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 350, 50));

        tblLabAssistant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name ", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLabAssistant);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 590, 120));

        btnView.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnView.setForeground(new java.awt.Color(153, 0, 51));
        btnView.setText("VIEW");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 100, 40));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(153, 0, 51));
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 100, 40));

        btnDelete.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(153, 0, 51));
        btnDelete.setText("DELETE");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 100, 40));

        lblname.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblname.setForeground(new java.awt.Color(153, 0, 51));
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname.setText("Name");
        jPanel1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 100, 30));

        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 170, 30));

        lblusername.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblusername.setForeground(new java.awt.Color(153, 0, 51));
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusername.setText("Username");
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 110, 30));

        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 170, 30));

        lblpassword.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(153, 0, 51));
        lblpassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpassword.setText("Password");
        jPanel1.add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 120, 30));

        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 170, 30));

        btnadd.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnadd.setForeground(new java.awt.Color(153, 0, 51));
        btnadd.setText("ADD LAB ASSISTANT");
        btnadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 200, 40));

        jPanel2.setBackground(new java.awt.Color(102, 0, 51));

        lblManageInfo1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblManageInfo1.setForeground(new java.awt.Color(255, 255, 255));
        lblManageInfo1.setText("HOSPITAL ADMIN WORK AREA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(433, Short.MAX_VALUE)
                .addComponent(lblManageInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblManageInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ipcuserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) ipcuserProcessContainer.getLayout();
        layout.previous(ipcuserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

        int ipcselectRow = tblLabAssistant.getSelectedRow();
        if (ipcselectRow >= 0) {
            String ipcname = (String) tblLabAssistant.getValueAt(ipcselectRow, 0);
            String ipcusername = (String) tblLabAssistant.getValueAt(ipcselectRow, 1);
            String ipcpassword = (String) tblLabAssistant.getValueAt(ipcselectRow, 2);

            txtname.setText(ipcname + "");
            txtusername.setText(ipcusername + "");
            txtpass.setText(ipcpassword + "");
            btnadd.setEnabled(false);
        }
        else  {
            JOptionPane.showMessageDialog(null, "Please select a row to view the Lab Assistant");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int ipcselectRow = tblLabAssistant.getSelectedRow();
        if (ipcselectRow >= 0) {
            String ipcname = (String) tblLabAssistant.getValueAt(ipcselectRow, 0);
            String ipcusername = (String) tblLabAssistant.getValueAt(ipcselectRow, 1);
            String ipcpassword = (String) tblLabAssistant.getValueAt(ipcselectRow, 2);
            ipcaccount = ipcsystem.getUserAccountDirectory().authenticateUser(ipcusername, ipcpassword);
            ipcsystem.getUserAccountDirectory().updateUserAccount(ipcaccount, txtname.getText(), txtusername.getText(), txtpass.getText());
            ipcpopulateLabAssistantTable();

            txtname.setText("");
            txtusername.setText("");
            txtpass.setText("");
            btnadd.setEnabled(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to update the Lab Assistant");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int ipcselectedRow = tblLabAssistant.getSelectedRow();
        if (ipcselectedRow >= 0) {
            int ipcselectionButton = JOptionPane.YES_NO_OPTION;
            int ipcselectionResult = JOptionPane.showConfirmDialog(null, "Confirm delete?", "Warning", ipcselectionButton);
            if (ipcselectionResult == JOptionPane.YES_OPTION) {
                String ipcusername = (String) tblLabAssistant.getValueAt(ipcselectedRow, 1);
                String ipcpwd = (String) tblLabAssistant.getValueAt(ipcselectedRow, 2);
                UserAccount ipcuser = ipcsystem.getUserAccountDirectory().authenticateUser(ipcusername, ipcpwd);

                ipcsystem.getUserAccountDirectory().deleteUserAccount(ipcuser);
                ipcsystem.getLabAssistantDirectory().deleteLabAssistant(ipcuser.getIpcuserName());
                ipcpopulateLabAssistantTable();
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Please select a row to delete the Lab Assistant");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:

        UserAccount ipcuserAccount = ipcsystem.getUserAccountDirectory().createUserAccount(txtname.getText(),txtusername.getText(), txtpass.getText(), null, new LabAssistantRole());
        LabAssistant labAssistant = ipcsystem.getLabAssistantDirectory().createUserAccount(txtusername.getText());
        ipcpopulateLabAssistantTable();
        for (Hospital hospital : ipcsystem.getHospitalDirectory().getHospitalDirectory()) {
            if (hospital.getIpcuserName().equals(ipcaccount.getIpcuserName())) {
                ipcsystem.getLabAssistantDirectory().updateLabAssistantHospitalInfo(labAssistant, hospital.getIpcuserName());
            }
        }
        txtname.setText("");
        txtpass.setText("");
        txtusername.setText("");

        JOptionPane.showMessageDialog(this, "Lab Assistant details added ");

    }//GEN-LAST:event_btnaddActionPerformed

private void ipcpopulateLabAssistantTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblLabAssistant.getModel();
        tablemodel.setRowCount(0);
        
         for (UserAccount user : ipcsystem.getUserAccountDirectory().getUserAccountList()) {

            if (user.getRole().getClass().getName().equals("IntensivePetCare.Role.LabAssistantRole")) {
                Object[] row = new Object[3];
                row[0] = user.getIpcname();
                row[1] = user.getIpcuserName();
                row[2] = user.getIpcpassword();
                tablemodel.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnadd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageInfo1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTable tblLabAssistant;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

private boolean ipcvalidateInputFields() {

        Pattern p = Pattern.compile("^[A-Za-z0-9 ]+$");
        Matcher m = p.matcher(txtname.getText());
        
        Pattern p7 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m7 = p7.matcher(txtusername.getText());
        
        Pattern p1 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m1 = p1.matcher(txtpass.getText());
        
        
        if (!m.matches()) {

            JOptionPane.showMessageDialog(this, "Error in provided name,Please Try agian!");
            return false;
        } else if (!m7.matches()) {

            JOptionPane.showMessageDialog(this, "Error in provided username ,Please Try agian!");
            return false;
        }
        else if (!m1.matches()) {

            JOptionPane.showMessageDialog(this, "Error in provided password ,Please Try agian!");
            return false;
        }
        else {
            return true;
        }
    }

}
