/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.HospitalAdmin;
import Model.Ecosystem;
import java.awt.CardLayout;
import Model.FundRaising.FundRaising;
import javax.swing.JOptionPane;
import Model.PetVolunteer.PetVolunteer;
import javax.swing.JPanel;
import Model.Vet.Vet;
import javax.swing.table.DefaultTableModel;
import Model.UserAccount.UserAccount;



/**
 *
 * @author saran
 */
public class ManagePetInfo extends javax.swing.JPanel {

    /**
     * Creates new form ManagePetInfo
     */
    JPanel ipcUserProcessContainer;
    Ecosystem ipcSystem;
    private UserAccount ipcAccount;
    
    public ManagePetInfo(JPanel ipcUserProcessContainer,UserAccount ipcAccount, Ecosystem ipcSystem) {
        initComponents();
        this.ipcUserProcessContainer= ipcUserProcessContainer;
        this.ipcSystem = ipcSystem;
        this.ipcAccount = ipcAccount;
        ipcPopulatePetInfo();
        ipcPopulateVetTable();
    }
    
    public void ipcPopulatePetInfo() {
        
        DefaultTableModel tablemodel = (DefaultTableModel) tb1.getModel();
        tablemodel.setRowCount(0);
        for (PetVolunteer petVolunteer : ipcSystem.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
            if (petVolunteer.getIpchospitalName().equals(ipcAccount.getIpcname())) {
                Object[] row = new Object[5];
                row[0] = petVolunteer;
                row[1] = petVolunteer.getIpcName();
//                row[2] = petVolunteer.getUsername();
                row[2] = petVolunteer.getIpcpetType();
                row[3] = petVolunteer.getIpchealthCamp();
                row[4] = petVolunteer.getIpclabResultStatus() == null ? "N/A" : petVolunteer.getIpclabResultStatus();
                tablemodel.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        lb3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(63, 40, 101));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 51));

        lb1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("HOSPITAL ADMIN WORK AREA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1070, -1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 575));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "pet username", "pet owner", "pet type", "Health Camp", "Lab result status"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 640, 180));

        btn1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btn1.setForeground(new java.awt.Color(153, 0, 0));
        btn1.setText("ADD VET");
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 150, 30));

        btn2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btn2.setForeground(new java.awt.Color(153, 0, 51));
        btn2.setText("ADD FUNDRAISER");
        btn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 150, 30));

        lb3.setBackground(new java.awt.Color(255, 255, 255));
        lb3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lb3.setForeground(new java.awt.Color(153, 0, 51));
        lb3.setText("VET NAME");
        jPanel3.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 100, 30));

        txt1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel3.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 150, 30));

        lb2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lb2.setForeground(new java.awt.Color(153, 0, 51));
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("ASSIGN PET TO VET");
        jPanel3.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 170, 360, 60));

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Vet username"
            }
        ));
        jScrollPane2.setViewportView(tb2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 500, 100));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 40, 101));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ASSIGN PET TO VET");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 360, 60));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(63, 40, 101));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ASSIGN PET TO VET");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 360, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1049, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        int ipcselectedRow = tb1.getSelectedRow();
        PetVolunteer ipcvetSelected = (PetVolunteer) tb1.getValueAt(ipcselectedRow, 0);
        String ipcvetPetOwner = ipcvetSelected.getIpcName();
        String ipcvetPetType = ipcvetSelected.getIpcpetType();
        String ipcvetHealthCamp = ipcvetSelected.getIpchealthCamp();
        String ipcvetHospitalName = ipcvetSelected.getIpchospitalName();
        for(Vet vet: ipcSystem.getVetDirectory().getVetDirectory()) {
            if(vet.getIpcuserName().equals(txt1.getText())){
                ipcSystem.getVetDirectory().updateVetInfo(vet, ipcvetPetOwner, ipcvetPetType, ipcvetHealthCamp, ipcvetHospitalName);
            }
        }
        JOptionPane.showMessageDialog(this, "Vet details has been added Successfuly");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        int ipcselectedRow = tb1.getSelectedRow();
        PetVolunteer ipcvetSelected = (PetVolunteer) tb1.getValueAt(ipcselectedRow, 0);
        String ipcvetPetOwner = ipcvetSelected.getIpcName();
        String ipcvetPetType = ipcvetSelected.getIpcpetType();
        String ipcvetHealthCamp = ipcvetSelected.getIpchealthCamp();
        String ipcvetHospitalName = ipcvetSelected.getIpchospitalName();
        for(FundRaising fundRaising: ipcSystem.getFundRaisingDirectory().getFundRaisingDirectory()) {
            ipcSystem.getFundRaisingDirectory().updateFundRaisingInfo(fundRaising, ipcvetPetOwner, ipcvetPetType, ipcvetHealthCamp, ipcvetHospitalName);
            System.out.println("Fund raising agency has been added sucessfully");
        }
        JOptionPane.showMessageDialog(this, "Request has been sent to the Fundraising successfully");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        ipcUserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) ipcUserProcessContainer.getLayout();
        layout.previous(ipcUserProcessContainer);
    }//GEN-LAST:event_btn3ActionPerformed

private void ipcPopulateVetTable() {
        
        DefaultTableModel tablemodel = (DefaultTableModel) tb2.getModel();
        tablemodel.setRowCount(0);
        
        for(Vet vet: ipcSystem.getVetDirectory().getVetDirectory()){
            System.out.println("vet name :" + vet.getIpchospitalName());
            System.out.println("account name :" + ipcAccount.getIpcname());
            if(vet.getIpchospitalName().equals(ipcAccount.getIpcname())) {
                Object[] row = new Object[1];
                System.out.println("here");
                row[0] = vet;
                tablemodel.addRow(row);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
