/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hospital;
import Model.Ecosystem;
import Model.LabAssistant.LabAssistant;
import Model.PetVolunteer.PetVolunteer;
import Model.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author saran
 */
public class LabAssistantWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form LabAssistantWorkArea
     */
    
    JPanel ipcuserProcessContainer;
    Ecosystem ipcsystem;
    private UserAccount ipcaccount;
    
    public LabAssistantWorkArea(JPanel ipcuserProcessContainer, UserAccount ipcaccount, Ecosystem ipcsystem) {
        initComponents();
        
        this.ipcuserProcessContainer = ipcuserProcessContainer;
        this.ipcsystem = ipcsystem;
        this.ipcaccount = ipcaccount;
        ipcpopulateTable();
    }

    public void ipcpopulateTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tbllabassitant.getModel();
        tablemodel.setRowCount(0);
        for (LabAssistant labAssistant : ipcsystem.getLabAssistantDirectory().getLabAssistantDirectory()) {
            if (labAssistant.getIpcuserName().equals(ipcaccount.getIpcuserName())) {
                System.out.println("Lab assistant : " + labAssistant.getIpcuserName());
                System.out.println("Lab assistant : " + labAssistant.getIpcpetOwner());
                System.out.println("Lab assistant : " + labAssistant.getIpcpetType());
                Object[] row = new Object[4];
                row[0] = labAssistant.getIpcpetOwner();
                row[1] = labAssistant.getIpcpetType();
                row[2] = labAssistant.getIpchealthCamp();
                row[3] = labAssistant.getIpclabResultStatus() == null ? "N/A" : labAssistant.getIpclabResultStatus();
                tablemodel.addRow(row);
            }

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbllabassitant = new javax.swing.JTable();
        lbllabresult = new javax.swing.JLabel();
        txtlabresult = new javax.swing.JTextField();
        btnchangestatus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblManageInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbllabassitant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pet Owner", "Pet Type", "Health Camp", "Test Result"
            }
        ));
        jScrollPane1.setViewportView(tbllabassitant);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 730, 170));

        lbllabresult.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lbllabresult.setForeground(new java.awt.Color(153, 0, 0));
        lbllabresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllabresult.setText("RESULT OF LAB TEST");
        add(lbllabresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 210, 30));

        txtlabresult.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtlabresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 220, 30));

        btnchangestatus.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnchangestatus.setForeground(new java.awt.Color(153, 0, 51));
        btnchangestatus.setText("UPDATE STATUS");
        btnchangestatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnchangestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangestatusActionPerformed(evt);
            }
        });
        add(btnchangestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 140, 30));

        jPanel1.setBackground(new java.awt.Color(102, 0, 51));

        lblManageInfo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblManageInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblManageInfo.setText("LAB REPRESENTATIVE MANAGEMENT ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(lblManageInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblManageInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Change the status of lab tests here !!");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnchangestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangestatusActionPerformed
        // TODO add your handling code here:
        String ipcstatus = txtlabresult.getText();
        for(LabAssistant labAssistant: ipcsystem.getLabAssistantDirectory().getLabAssistantDirectory()) {
            ipcsystem.getLabAssistantDirectory().updateLabAssistantTestResult(labAssistant, ipcstatus);
            System.out.println("Lab result has been updated successfully");
        }
        for(LabAssistant labAssistant: ipcsystem.getLabAssistantDirectory().getLabAssistantDirectory()) {
            for(PetVolunteer petVolunteer: ipcsystem.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
                if(petVolunteer.getIpcName().equals(labAssistant.getIpcpetOwner())){
                    ipcsystem.getPetVolunteerDirectory().updatePetVolunteerLabStatus(petVolunteer, ipcstatus);
                    System.out.println("Lab status has been updated successfully");
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Lab results has been updated successfully ");
        ipcpopulateTable();
    }//GEN-LAST:event_btnchangestatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchangestatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageInfo;
    private javax.swing.JLabel lbllabresult;
    private javax.swing.JTable tbllabassitant;
    private javax.swing.JTextField txtlabresult;
    // End of variables declaration//GEN-END:variables
}
