/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hospital;

import javax.swing.JOptionPane;
import Model.Ecosystem;
import Model.PetVolunteer.PetVolunteer;
import javax.swing.JPanel;
import Model.LabAssistant.LabAssistant;
import javax.swing.table.DefaultTableModel;
import Model.Vet.Vet;

/**
 *
 * @author saran
 */
public class VetWorkarea extends javax.swing.JPanel {

    /**
     * Creates new form VetWorkarea
     */
    
    JPanel ipcUserProcessContainer;
    Ecosystem ipcSystem;
    
    public VetWorkarea(JPanel ipcuserProcessContainer, Ecosystem ipcSystem) {
        initComponents();
        
        this.ipcUserProcessContainer = ipcUserProcessContainer;
        this.ipcSystem = ipcSystem;
        ipcPopulateVetTable();
    }

private void ipcPopulateVetTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tb1.getModel();
        for(PetVolunteer petVolunteer : ipcSystem.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
            for(Vet vet: ipcSystem.getVetDirectory().getVetDirectory()) {
                System.out.println("pet volunteer hosp name : " + petVolunteer.getIpchospitalName() );
                System.out.println("vet hosp name : " + vet.getIpchospitalName() );
                if(vet.getIpchospitalName().equals(petVolunteer.getIpchospitalName())){
                    Object[] row = new Object[4];
                    row[0] = vet;
                    row[1] = vet.getIpcpetOwner();
                    row[2] = vet.getIpcpetType();
                    row[3] = vet.getIpchealthCamp();
                    tablemodel.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        btn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vet Name", "Pet Owner", "Pet Type", "Health Camp"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 770, 170));

        btn1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btn1.setForeground(new java.awt.Color(63, 40, 101));
        btn1.setText("ALLOCATE/ASSIGN LAB");
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 230, 40));

        jPanel1.setBackground(new java.awt.Color(102, 0, 51));

        lb1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("LAB REPRESENTATIVE MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(543, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        int ipcselectedRow = tb1.getSelectedRow();
        Vet vetSelected = (Vet) tb1.getValueAt(ipcselectedRow, 0);
        for(LabAssistant labAssistant: ipcSystem.getLabAssistantDirectory().getLabAssistantDirectory()) {
            for(Vet vet: ipcSystem.getVetDirectory().getVetDirectory()) {
                if(vet.getIpchospitalName().equals(labAssistant.getIpchospitalName())) {
                    System.out.println("selected vet : " + vetSelected.getIpcuserName() + " " + vetSelected.getIpchealthCamp());
                    ipcSystem.getLabAssistantDirectory().updateLabAssistantInfo(labAssistant, vetSelected.getIpcuserName(), vetSelected.getIpcpetOwner(),vetSelected.getIpcpetType(),vetSelected.getIpchealthCamp());
                    System.out.println(" Assigning Lab assistant has been completed successfully");
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Assigning Lab assistant has been completed successfully");
    }//GEN-LAST:event_btn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables



}
