/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthCamp;
import Model.Driver.Driver;
import Model.Ecosystem;
import Model.HealthCamp.HealthCamp;
import Model.Hospital.Hospital;
import Model.PetVolunteer.PetVolunteer;
import Model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author poojitha
 */
public class ManagePetVolunteer extends javax.swing.JPanel {

    /**
     * Creates new form ManagePetVolunteer
     */
    JPanel userProcessContainer;
    Ecosystem system;
    UserAccount account;

    public ManagePetVolunteer(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;

        populatePetVolunteerTable();
        populateHospitalTable();
        populateDriverTable();
    }
    public void populatePetVolunteerTable() {
        String healthCampName = null;
        for (HealthCamp healthCamp : system.getHealthCampDirectory().getHealthCampDirectory()) {
            if (healthCamp.getIpcuserName().equals(account.getIpcuserName())) {
                healthCampName = healthCamp.getIpchealthCampName();
            }
        }

        DefaultTableModel tablemodel = (DefaultTableModel) tblPetVolunteerHealthCamp.getModel();
        tablemodel.setRowCount(0);

        for (PetVolunteer petVolunteer : system.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
            if (petVolunteer.getIpchealthCamp().equals(healthCampName)) {
                Object[] row = new Object[4];
                row[0] = petVolunteer;
                row[2] = petVolunteer.getIpcuserName();
                row[1] = petVolunteer.getIpcpetType();
                row[3] = petVolunteer.getIpchealthCamp();

                tablemodel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetVolunteerHealthCamp = new javax.swing.JTable();
        lblpetowner = new javax.swing.JLabel();
        txtpetowner = new javax.swing.JTextField();
        lblpettype = new javax.swing.JLabel();
        txtpettype = new javax.swing.JTextField();
        lblorgname = new javax.swing.JLabel();
        txtorgname = new javax.swing.JTextField();
        jComboBoxHealth = new javax.swing.JComboBox<>();
        lblhealthstatus = new javax.swing.JLabel();
        btnRegisterForHospital = new javax.swing.JButton();
        lblhospitalname = new javax.swing.JLabel();
        txthospitalname = new javax.swing.JTextField();
        lbldriver = new javax.swing.JLabel();
        txtdriver = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPetUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHospitals = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDrivers = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPetVolunteerHealthCamp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pet Owner", "Pet Type", "Pet username", "Org name"
            }
        ));
        jScrollPane1.setViewportView(tblPetVolunteerHealthCamp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 570, 113));

        lblpetowner.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblpetowner.setForeground(new java.awt.Color(204, 0, 51));
        lblpetowner.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpetowner.setText("PET OWNER");
        jPanel1.add(lblpetowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 120, 20));

        txtpetowner.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        txtpetowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpetownerActionPerformed(evt);
            }
        });
        jPanel1.add(txtpetowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 130, 20));

        lblpettype.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblpettype.setForeground(new java.awt.Color(204, 0, 51));
        lblpettype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpettype.setText("PET TYPE");
        jPanel1.add(lblpettype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, 20));

        txtpettype.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.add(txtpettype, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 130, 20));

        lblorgname.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblorgname.setForeground(new java.awt.Color(204, 0, 0));
        lblorgname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblorgname.setText("ORGANISATION NAME");
        jPanel1.add(lblorgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 190, 20));

        txtorgname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.add(txtorgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 130, 20));

        jComboBoxHealth.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jComboBoxHealth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good", "Bad" }));
        jComboBoxHealth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxHealth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHealthItemStateChanged(evt);
            }
        });
        jComboBoxHealth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxHealthMousePressed(evt);
            }
        });
        jPanel1.add(jComboBoxHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 140, 20));

        lblhealthstatus.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblhealthstatus.setForeground(new java.awt.Color(204, 0, 51));
        lblhealthstatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblhealthstatus.setText("HEALTH STATUS");
        jPanel1.add(lblhealthstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 150, 20));

        btnRegisterForHospital.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnRegisterForHospital.setForeground(new java.awt.Color(204, 0, 51));
        btnRegisterForHospital.setText("SIGN UP FOR HOSPITAL");
        btnRegisterForHospital.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterForHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterForHospitalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegisterForHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 180, 30));

        lblhospitalname.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblhospitalname.setForeground(new java.awt.Color(204, 0, 51));
        lblhospitalname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblhospitalname.setText("HOSPITAL NAME");
        jPanel1.add(lblhospitalname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 150, 20));

        txthospitalname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.add(txthospitalname, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 140, 20));

        lbldriver.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lbldriver.setForeground(new java.awt.Color(204, 0, 51));
        lbldriver.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldriver.setText("DRIVER");
        jPanel1.add(lbldriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 130, 20));

        txtdriver.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        txtdriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdriverActionPerformed(evt);
            }
        });
        jPanel1.add(txtdriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 150, 20));

        btnView.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnView.setForeground(new java.awt.Color(204, 0, 51));
        btnView.setText("VIEW");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 90, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("PET USERNAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 130, 20));

        txtPetUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.add(txtPetUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 130, 20));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MANAGE PET VOLUNTEER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 430, 50));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-arrow-64 (2) (1).png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, 40));

        tblHospitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Hospital Name"
            }
        ));
        jScrollPane2.setViewportView(tblHospitals);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 160, 110));

        tblDrivers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Driver name"
            }
        ));
        jScrollPane3.setViewportView(tblDrivers);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 150, 110));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -40, 930, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxHealthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHealthItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHealthItemStateChanged

    private void jComboBoxHealthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxHealthMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHealthMousePressed

    private void btnRegisterForHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterForHospitalActionPerformed
        // TODO add your handling code here:
        if(validateInputFields()){

            for (PetVolunteer petVolunteer : system.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
                if (petVolunteer.getIpcuserName().equals(txtPetUsername.getText())) {
                    system.getPetVolunteerDirectory().updatePetVolunteerHospitalInfo(petVolunteer, txthospitalname.getText(), txtdriver.getText());
                }
            }

            for (Driver driver : system.getDriverDirectory().getDriverDirectory()) {
                if (driver.getIpcuserName().equals(txtdriver.getText())) {
                    system.getDriverDirectory().updateDriverHealthCampInfo(driver, txtPetUsername.getText(), txtpettype.getText(), txtorgname.getText(), txthospitalname.getText());
                }
            }

            JOptionPane.showMessageDialog(this, "Pet has been registerd successfully for the hospital ");
        }
    }//GEN-LAST:event_btnRegisterForHospitalActionPerformed

    private void txtdriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdriverActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPetVolunteerHealthCamp.getSelectedRow();
        if (selectedRow <0){
            JOptionPane.showMessageDialog(this, "Please Select a row to view");
            return;
        }
        PetVolunteer petVolunterSelected = (PetVolunteer) tblPetVolunteerHealthCamp.getValueAt(selectedRow, 0);
        txtpetowner.setText(petVolunterSelected.getIpcName());
        txtorgname.setText(petVolunterSelected.getIpchealthCamp());
        txtpettype.setText(petVolunterSelected.getIpcpetType());
        txtPetUsername.setText(petVolunterSelected.getIpcuserName());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtpetownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpetownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpetownerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterForHospital;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> jComboBoxHealth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbldriver;
    private javax.swing.JLabel lblhealthstatus;
    private javax.swing.JLabel lblhospitalname;
    private javax.swing.JLabel lblorgname;
    private javax.swing.JLabel lblpetowner;
    private javax.swing.JLabel lblpettype;
    private javax.swing.JTable tblDrivers;
    private javax.swing.JTable tblHospitals;
    private javax.swing.JTable tblPetVolunteerHealthCamp;
    private javax.swing.JTextField txtPetUsername;
    private javax.swing.JTextField txtdriver;
    private javax.swing.JTextField txthospitalname;
    private javax.swing.JTextField txtorgname;
    private javax.swing.JTextField txtpetowner;
    private javax.swing.JTextField txtpettype;
    // End of variables declaration//GEN-END:variables

private void populateHospitalTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblHospitals.getModel();
        tablemodel.setRowCount(0);

        for (Hospital hospital : system.getHospitalDirectory().getHospitalDirectory()) {
            Object[] row = new Object[1];
            row[0] = hospital;
            tablemodel.addRow(row);
        }
    }

    private void populateDriverTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblDrivers.getModel();
        tablemodel.setRowCount(0);

        for (Driver driver : system.getDriverDirectory().getDriverDirectory()) {
            Object[] row = new Object[1];
            row[0] = driver;
            tablemodel.addRow(row);
        }
    }

    private boolean validateInputFields() {

        Pattern p = Pattern.compile("^[A-Za-z0-9 ]+$");
        Matcher m = p.matcher(txthospitalname.getText());
        Pattern p7 = Pattern.compile("^[A-Za-z0-9]{3,14}+$");
        Matcher m7 = p7.matcher(txtdriver.getText());
        if (!m.matches()) {

            JOptionPane.showMessageDialog(this, "Error in provided input format for hospital,Please Try agian!");
            return false;
        } else if (!m7.matches()) {

            JOptionPane.showMessageDialog(this, "Error in provided input format for driver,Please Try agian!");
            return false;
        }     
        else {
            return true;
        }
    }
}       

