/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Driver;

import Model.Driver.Driver;
import Model.Ecosystem;
import Model.UserAccount.UserAccount;
import java.util.Properties;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import javax.mail;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author poojitha
 */
public class DriverWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form DriverWorkArea
     */
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;

    public DriverWorkArea(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDM = new javax.swing.JTable();
        lbUpdateStatus = new javax.swing.JLabel();
        txtUpdateStatus = new javax.swing.JTextField();
        btnUpdateStatus = new javax.swing.JButton();
        bntSendEmail = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbDM = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pet Owner", "Pet Type", "Health Camp", "Hospital Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblDM);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 790, 240));

        lbUpdateStatus.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbUpdateStatus.setForeground(new java.awt.Color(153, 0, 51));
        lbUpdateStatus.setText("Update Status ");
        add(lbUpdateStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 470, 100, -1));

        txtUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateStatusActionPerformed(evt);
            }
        });
        add(txtUpdateStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 180, -1));

        btnUpdateStatus.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(153, 0, 51));
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });
        add(btnUpdateStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 132, 41));

        bntSendEmail.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bntSendEmail.setForeground(new java.awt.Color(153, 0, 51));
        bntSendEmail.setText("Send Email");
        bntSendEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSendEmailActionPerformed(evt);
            }
        });
        add(bntSendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 126, 41));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        lbDM.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbDM.setForeground(new java.awt.Color(255, 255, 255));
        lbDM.setText("DRIVER MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addComponent(lbDM, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(413, 413, 413))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbDM, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 90));

        lbWelcome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbWelcome.setForeground(new java.awt.Color(153, 0, 0));
        lbWelcome.setText("You are now viewing the driver management profile!!");
        add(lbWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 380, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateStatusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUpdateStatusActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO add your handling code here:
        for(Driver driver: system.getDriverDirectory().getDriverDirectory()) {
            if(account.getIpcuserName().equals(driver.getIpcuserName())) {
                system.getDriverDirectory().updateDropOffStatus(driver,txtUpdateStatus.getText());
            }
        }
        populateTable();
        
    }                                               

    public void populateTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblDM.getModel();
        tablemodel.setRowCount(0);
        for(Driver driver: system.getDriverDirectory().getDriverDirectory()) {
            if(account.getIpcuserName().equals(driver.getIpcuserName())) {
                Object[] row = new Object[5];
                row[0] = driver.getIpcpetOwner();
                row[1] = driver.getIpcpetType();
                row[2] = driver.getIpchealthCamp();
                row[3] = driver.getIpchospitalName();
                row[4] = driver.getIpcdropOffStatus() == null ? "N/A" : driver.getIpcdropOffStatus();
                tablemodel.addRow(row);
            }
        }
    
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void bntSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSendEmailActionPerformed
        // TODO add your handling code here:
        sendMailToPetOwner("poojitha.mandali@gmail.com","","");
    }//GEN-LAST:event_bntSendEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSendEmail;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDM;
    private javax.swing.JLabel lbUpdateStatus;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JTable tblDM;
    private javax.swing.JTextField txtUpdateStatus;
    // End of variables declaration//GEN-END:variables

    public void sendMailToPetOwner(String toMail, String msg, String username){
        System.out.println("Now start sending Email!");
        final String usname = "saranya73.n@gmail.com";
        final String passwrd = "Ipc@123";
        
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        //props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth","true");
        props.put("mail.smtp.starttls.enable", "true");
        //props.put("mail.smtp.port","465");
        
        Session session=Session.getDefaultInstance(props,
             new javax.mail.Authenticator() {
             protected PasswordAuthentication getPasswordAuthentication(){
                 return new PasswordAuthentication(usname,passwrd);
                }
             });
        
        try{
         Message message=new MimeMessage(session);
         message.setFrom(new InternetAddress("poojitha.mandali@gmail.com"));
         message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toMail));
         message.setSubject("Status Update ");
         message.setContent("<font color=black> Your pet is at the location dropped safely ! <b>" +
                 "<font color=black> Have a great day ! <b>","text/html");

         Transport.send(message);
         JOptionPane.showMessageDialog(null, "Destination reached - pet at location!");
     }
        catch(MessagingException e){
        e.printStackTrace();

        }
    }
}

