/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SystemAdminWorkArea;


import IntensivePetCare.Ecosystem;
import IntensivePetCare.PetVolunteer.PetVolunteer;
import IntensivePetCare.Role.PetVolunteerRole;
import IntensivePetCare.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author varshakuruva
 */
public class ManagePetVolunteer extends javax.swing.JPanel {

    /**
     * Creates new form ManagePetVolunteer
     */
    
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount user;
    
    public ManagePetVolunteer(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populatePetVolunteerTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblPetVolunteer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetVolunteer = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 209, 222));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-arrow-64 (2) (1).png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 20, 40, 30));

        lblPetVolunteer.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblPetVolunteer.setForeground(new java.awt.Color(63, 40, 101));
        lblPetVolunteer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPetVolunteer.setText("MANAGE PET VOLUNTEER");
        add(lblPetVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 42, 420, 50));

        tblPetVolunteer.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tblPetVolunteer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name ", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPetVolunteer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 97, 409, 100));

        btnView.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnView.setForeground(new java.awt.Color(63, 40, 101));
        btnView.setText("VIEW");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 232, 70, 30));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(63, 40, 101));
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 232, 80, 30));

        btnDelete.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(63, 40, 101));
        btnDelete.setText("DELETE");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 232, 80, 30));

        txtName.setForeground(new java.awt.Color(0, 153, 153));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 283, 190, 30));

        txtUserName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 153, 153));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 343, 190, 30));

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 153, 153));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 403, 190, 30));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(63, 40, 101));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("PASSWORD");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 403, 180, 30));

        lblUserName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(63, 40, 101));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("USERNAME");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 343, 180, 30));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(63, 40, 101));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("NAME");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 283, 170, 30));

        btnSubmit.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(63, 40, 101));
        btnSubmit.setText("SUBMIT");
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 469, 110, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/How-to-Start-an-Animal-Rescue-featured.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectRow = tblPetVolunteer.getSelectedRow();

        if (selectRow >= 0) {
            String name = (String) tblPetVolunteer.getValueAt(selectRow, 0);
            String username = (String) tblPetVolunteer.getValueAt(selectRow, 1);
            String password = (String) tblPetVolunteer.getValueAt(selectRow, 2);

            txtName.setText(name + "");
            txtUserName.setText(username + "");
            txtPassword.setText(password + "");
        }
        else  
        {
            JOptionPane.showMessageDialog(null, "Please select a row to view the PetVolunteer details");
        }  
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectRow = tblPetVolunteer.getSelectedRow();
        if (selectRow >= 0) {
        String name = (String) tblPetVolunteer.getValueAt(selectRow, 0);
        String username = (String) tblPetVolunteer.getValueAt(selectRow, 1);
        String password = (String) tblPetVolunteer.getValueAt(selectRow, 2);
        user = system.getUserAccountDirectory().authenticateUser(username, password);
        system.getUserAccountDirectory().updateUserAccount(user, txtName.getText(), txtUserName.getText(), txtPassword.getText());
        populatePetVolunteerTable();

        txtName.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        }
        else  
        {
            JOptionPane.showMessageDialog(null, "Please select a row to update the PetVolunteer details");
        }  
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPetVolunteer.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Confirm delete?", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                String username = (String) tblPetVolunteer.getValueAt(selectedRow, 1);
                String pwd = (String) tblPetVolunteer.getValueAt(selectedRow, 2);
                UserAccount user = system.getUserAccountDirectory().authenticateUser(username, pwd);

                system.getUserAccountDirectory().deleteUserAccount(user);
                system.getHospitalDirectory().deleteHospital(user.getIpcuserName());
                populatePetVolunteerTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete the PetVolunteer details");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUserName.getText())) {
            UserAccount userAccount = system.getUserAccountDirectory().createUserAccount(txtName.getText(), txtUserName.getText(), txtPassword.getText(), null, new PetVolunteerRole());
            PetVolunteer petVolunteer = system.getPetVolunteerDirectory().createUserAccount(txtUserName.getText());
            populatePetVolunteerTable();
            txtName.setText("");
            txtUserName.setText("");
            txtPassword.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Username is not unique");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    
    public void populatePetVolunteerTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblPetVolunteer.getModel();

        tablemodel.setRowCount(0);
        for (UserAccount user : system.getUserAccountDirectory().getUserAccountList()) {

            if (user.getRole().getClass().getName().equals("IntensivePetCare.Role.PetVolunteerRole")) {
                Object[] row = new Object[3];
                row[0] = user.getIpcname();
                row[1] = user.getIpcuserName();
                row[2] = user.getIpcpassword();
                tablemodel.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPetVolunteer;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblPetVolunteer;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

private boolean validateInputFields() {

        Pattern p = Pattern.compile("^[A-Za-z0-9 ]+$");
        Matcher m = p.matcher(txtName.getText());
        
        Pattern p7 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m7 = p7.matcher(txtUserName.getText());
        
        Pattern p1 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m1 = p1.matcher(txtPassword.getText());
        
        
        if (!m.matches()) {

            JOptionPane.showMessageDialog(this, "Error in provided name,Please Try agian!");
            return false;
        } else if (!m7.matches()) {

            JOptionPane.showMessageDialog(this, "Error in provided username ,Please Try agian!");
            return false;
        }
        else if (!m1.matches()) {

            JOptionPane.showMessageDialog(this, "Error in provided password ,Please Try agian!");
            return false;
        }
        else {
            return true;
        }
    }
}


