/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SystemAdminWorkArea;

import Model.UserAccount.UserAccount;
import Model.Hospital.Hospital;
import Model.Role.HospitalAdminRole;
import Model.Ecosystem;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.table.DefaultTableModel;
import javax.swing.Timer;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
/**
 *
 * @author varshakuruva
 */
public class ManageHospitalNetwork extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospitalNetwork
     */
    
    JPanel ipcUserProcessContainer;
    Ecosystem ipcSystem;
    private UserAccount user;
    
    public ManageHospitalNetwork(JPanel ipcUserProcessContainer, Ecosystem ipcSystem) {
        initComponents();
        
        this.ipcUserProcessContainer = ipcUserProcessContainer;
        this.ipcSystem = ipcSystem;
        ipcPopulateHospitalTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblManageHospNetwork = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        btnViewHospital = new javax.swing.JButton();
        btnDeleteHospital = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblUserName1 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnAddHospital = new javax.swing.JButton();
        btnUpdateHospital1 = new javax.swing.JButton();
        lblUserName2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(199, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-arrow-64 (2) (1).png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 40));

        lblManageHospNetwork.setBackground(new java.awt.Color(0, 153, 153));
        lblManageHospNetwork.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblManageHospNetwork.setForeground(new java.awt.Color(153, 0, 0));
        lblManageHospNetwork.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageHospNetwork.setText("MANAGE HOSPITAL NETWORK");
        add(lblManageHospNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 370, 87));

        tblHospital.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tblHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "UserName", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHospital);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 91));

        btnViewHospital.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnViewHospital.setForeground(new java.awt.Color(153, 0, 0));
        btnViewHospital.setText("VIEW");
        btnViewHospital.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalActionPerformed(evt);
            }
        });
        add(btnViewHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 30));

        btnDeleteHospital.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnDeleteHospital.setForeground(new java.awt.Color(153, 0, 0));
        btnDeleteHospital.setText("DELETE");
        btnDeleteHospital.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHospitalActionPerformed(evt);
            }
        });
        add(btnDeleteHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 90, 30));

        txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 153, 153));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 180, 30));

        txtUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 180, 30));

        lblUserName1.setBackground(new java.awt.Color(0, 153, 153));
        lblUserName1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblUserName1.setForeground(new java.awt.Color(153, 0, 51));
        lblUserName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserName1.setText("NAME");
        add(lblUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 260, 210, 30));

        lblPassword.setBackground(new java.awt.Color(0, 153, 153));
        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 0, 0));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("PASSWORD");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 350, 210, 30));

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 153, 153));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 180, 30));

        btnAddHospital.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnAddHospital.setForeground(new java.awt.Color(153, 0, 51));
        btnAddHospital.setText("ADD HOSPITAL NETWORK");
        btnAddHospital.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalActionPerformed(evt);
            }
        });
        add(btnAddHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 230, 40));

        btnUpdateHospital1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnUpdateHospital1.setForeground(new java.awt.Color(153, 0, 0));
        btnUpdateHospital1.setText("UPDATE");
        btnUpdateHospital1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateHospital1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHospital1ActionPerformed(evt);
            }
        });
        add(btnUpdateHospital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 100, 30));

        lblUserName2.setBackground(new java.awt.Color(0, 153, 153));
        lblUserName2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblUserName2.setForeground(new java.awt.Color(153, 0, 0));
        lblUserName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserName2.setText("USERNAME");
        add(lblUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 210, 24));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/m1.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -10, 590, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ipcUserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) ipcUserProcessContainer.getLayout();
        layout.previous(ipcUserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalActionPerformed
        // TODO add your handling code here:
        int selectRow = tblHospital.getSelectedRow();

        if (selectRow >= 0) {
            String name = (String) tblHospital.getValueAt(selectRow, 0);
            String username = (String) tblHospital.getValueAt(selectRow, 1);
            String password = (String) tblHospital.getValueAt(selectRow, 2);

            txtName.setText(name + "");
            txtUsername.setText(username + "");
            txtPassword.setText(password + "");
        }
        else  
        {
            JOptionPane.showMessageDialog(null, "to view the Hospital network details, Please select a row");
        }         
             
    }//GEN-LAST:event_btnViewHospitalActionPerformed

    private void btnDeleteHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHospitalActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHospital.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Confirm delete?", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                String username = (String) tblHospital.getValueAt(selectedRow, 1);
                String pwd = (String) tblHospital.getValueAt(selectedRow, 2);
                UserAccount user = ipcSystem.getUserAccountDirectory().authenticateUser(username, pwd);

                ipcSystem.getUserAccountDirectory().deleteUserAccount(user);
                ipcSystem.getHospitalDirectory().deleteHospital(user.getIpcuserName());
                ipcPopulateHospitalTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "to delete the Hospital network details, Please select a row");
        }
    }//GEN-LAST:event_btnDeleteHospitalActionPerformed

    private void btnAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalActionPerformed
        // TODO add your handling code here:
        if (ipcSystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtUsername.getText())) {
            UserAccount userAccount = ipcSystem.getUserAccountDirectory().createUserAccount(txtName.getText(), txtUsername.getText(), txtPassword.getText(), null, new HospitalAdminRole());
            Hospital hospital = ipcSystem.getHospitalDirectory().createUserAccount(txtUsername.getText(), txtName.getText());
            ipcPopulateHospitalTable();
            txtName.setText("");
            txtUsername.setText("");
            txtPassword.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Username is not unique");
        }
    }//GEN-LAST:event_btnAddHospitalActionPerformed

    private void btnUpdateHospital1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHospital1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblHospital.getSelectedRow();
        if (selectedRow >= 0) {
        String name = (String) tblHospital.getValueAt(selectedRow, 0);
        String username = (String) tblHospital.getValueAt(selectedRow, 1);
        String password = (String) tblHospital.getValueAt(selectedRow, 2);
        user = ipcSystem.getUserAccountDirectory().authenticateUser(username, password);
        ipcSystem.getUserAccountDirectory().updateUserAccount(user, txtName.getText(), txtUsername.getText(), txtPassword.getText());
        ipcPopulateHospitalTable();

        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        
        } else {
            JOptionPane.showMessageDialog(null, "to update the Hospital network details, Please select a row");
        }
    }//GEN-LAST:event_btnUpdateHospital1ActionPerformed

    private void ipcPopulateHospitalTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblHospital.getModel();

        tablemodel.setRowCount(0);
        for (UserAccount user : ipcSystem.getUserAccountDirectory().getUserAccountList()) {

            if (user.getRole().getClass().getName().equals("IntensivePetCare.Role.HospitalAdminRole")) {
                Object[] row = new Object[3];
                row[0] = user.getIpcname();
                row[1] = user.getIpcuserName();
                row[2] = user.getIpcpassword();
                tablemodel.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHospital;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteHospital;
    private javax.swing.JButton btnUpdateHospital1;
    private javax.swing.JButton btnViewHospital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageHospNetwork;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JTable tblHospital;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

private boolean validateInputFields() {

        Pattern p = Pattern.compile("^[A-Za-z0-9 ]+$");
        Matcher m = p.matcher(txtName.getText());
        
        Pattern p7 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m7 = p7.matcher(txtUsername.getText());
        
        Pattern p1 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m1 = p1.matcher(txtPassword.getText());
        
        
        if (!m.matches()) {

            JOptionPane.showMessageDialog(this, "Please Try Again! Provided Name has Error");
            return false;
        } else if (!m7.matches()) {

            JOptionPane.showMessageDialog(this, "Please Try Again! Provided User Name has Error");
            return false;
        }
        else if (!m1.matches()) {

            JOptionPane.showMessageDialog(this, "Please Try Again! Provided Password has Error");
            return false;
        }
        else {
            return true;
        }
    }
}