/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SystemAdminWorkArea;

import Model.Sponsor.Sponsor;
import Model.UserAccount.UserAccount;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Ecosystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Model.Role.SponsorRole;
/**
 *
 * @author varshakuruva
 */
public class ManageSponsor extends javax.swing.JPanel {

    /**
     * Creates new form ManageSponsor
     */
    
    JPanel ipcUserProcessContainer;
    Ecosystem ipcSystem;
    private UserAccount user;

    public ManageSponsor(JPanel ipcUserProcessContainer, Ecosystem ipcSystem) {
        initComponents();
        this.ipcUserProcessContainer = ipcUserProcessContainer;
        this.ipcSystem = ipcSystem;
        ipcPopulateSponsorTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSponsors = new javax.swing.JTable();
        btnView1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lbPassword = new javax.swing.JLabel();
        btnSave1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 209, 222));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-arrow-64 (2) (1).png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 24, 38, 30));

        lb1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(153, 0, 0));
        lb1.setText("MANAGE SPONSORS");
        add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        tbSponsors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name ", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbSponsors);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 660, 160));

        btnView1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnView1.setForeground(new java.awt.Color(153, 0, 0));
        btnView1.setText("VIEW");
        btnView1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });
        add(btnView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 90, 30));

        btnUpdate1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(153, 0, 0));
        btnUpdate1.setText("UPDATE");
        btnUpdate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 70, 30));

        btnDelete1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(153, 0, 0));
        btnDelete1.setText("DELETE");
        btnDelete1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 70, 30));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 200, 30));

        lbName.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbName.setText("NAME");
        add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 90, 30));

        lbUserName.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUserName.setText("USERNAME");
        add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, 30));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 200, 30));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 200, 30));

        lbPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPassword.setText("PASSWORD");
        add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 130, 30));

        btnSave1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(153, 0, 0));
        btnSave1.setText("ADD SPONSOR");
        btnSave1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 120, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/ezgif.com-gif-maker (19) (1).gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1130, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        ipcUserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) ipcUserProcessContainer.getLayout();
        layout.previous(ipcUserProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:

        int selectRow = tbSponsors.getSelectedRow();

        if (selectRow >= 0) {
            String name = (String) tbSponsors.getValueAt(selectRow, 0);
            String username = (String) tbSponsors.getValueAt(selectRow, 1);
            String password = (String) tbSponsors.getValueAt(selectRow, 2);

            txtName.setText(name + "");
            txtUserName.setText(username + "");
            txtPassword.setText(password + "");
            btnSave1.setEnabled(false);
        }
        
        else  
        {
            JOptionPane.showMessageDialog(null, "to view the Sponsor details, Please select a row");
        }  
    }//GEN-LAST:event_btnView1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbSponsors.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Confirm delete?", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                String username = (String) tbSponsors.getValueAt(selectedRow, 1);
                String pwd = (String) tbSponsors.getValueAt(selectedRow, 2);
                UserAccount user = ipcSystem.getUserAccountDirectory().authenticateUser(username, pwd);

                ipcSystem.getUserAccountDirectory().deleteUserAccount(user);
                ipcSystem.getSponsorDirectory().deleteSponsor(user.getIpcuserName());
                ipcPopulateSponsorTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "to delete the Sponsor details, Please select a row");
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        if (ipcSystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtUserName.getText())) {
        UserAccount userAccount = ipcSystem.getUserAccountDirectory().createUserAccount(txtName.getText(), txtUserName.getText(), txtPassword.getText(), null, new SponsorRole());
        Sponsor sponsor = ipcSystem.getSponsorDirectory().createUserAccount(txtUserName.getText());
        JOptionPane.showMessageDialog(null, "Sponsor details added successfully");
        ipcPopulateSponsorTable();
        txtName.setText("");
        txtPassword.setText("");
        txtUserName.setText("");
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        
        int selectRow = tbSponsors.getSelectedRow();
        if (selectRow >= 0) {
        String name = (String) tbSponsors.getValueAt(selectRow, 0);
        String username = (String) tbSponsors.getValueAt(selectRow, 1);
        String password = (String) tbSponsors.getValueAt(selectRow, 2);
        user = ipcSystem.getUserAccountDirectory().authenticateUser(username, password);
        ipcSystem.getUserAccountDirectory().updateUserAccount(user, txtName.getText(), txtUserName.getText(), txtPassword.getText());
        ipcPopulateSponsorTable();

        txtName.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        }
        else  
        {
            JOptionPane.showMessageDialog(null, "to update the Sponsor details, Please select a row");
        }  
    }//GEN-LAST:event_btnUpdate1ActionPerformed
      private void ipcPopulateSponsorTable() {

        DefaultTableModel tablemodel = (DefaultTableModel) tbSponsors.getModel();
        tablemodel.setRowCount(0);

        for (UserAccount user : ipcSystem.getUserAccountDirectory().getUserAccountList()) {

            if (user.getRole().getClass().getName().equals("IntensivePetCare.Role.SponsorRole")) {
                Object[] row = new Object[3];
                row[0] = user.getIpcname();
                row[1] = user.getIpcuserName();
                row[2] = user.getIpcpassword();
                tablemodel.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnView1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTable tbSponsors;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

private boolean validateInputFields() {

        Pattern p = Pattern.compile("^[A-Za-z0-9 ]+$");
        Matcher m = p.matcher(txtName.getText());
        
        Pattern p7 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m7 = p7.matcher(txtUserName.getText());
        
        Pattern p1 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m1 = p1.matcher(txtPassword.getText());
        
        
        if (!m.matches()) {

            JOptionPane.showMessageDialog(this, "Please Try Again! Provided Name has Error");
            return false;
        } else if (!m7.matches()) {

            JOptionPane.showMessageDialog(this, "Please Try Again! Provided User Name has Error");
            return false;
        }
        else if (!m1.matches()) {

            JOptionPane.showMessageDialog(this, "Please Try Again! Provided Password has Error");
            return false;
        }
        else {
            return true;
        }
    }
}
